feat: Add REST api support
kothub/kothub pull request #13
Opened 2017-05-30 11:07 UTC by Astalaseven

(for review only, don't merge yet)

2017-05-30 11:29 UTC, fknop requested changes

2017-05-30 11:29 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/Base.kt
> +fun getObj(query: String, callback: (FuelError?, JSONObject?) -> Unit): Request {
getObj and getArr are almost the same functions

2017-05-30 11:29 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/Viewer.kt
> +    getArr("notifications", {
You can close the parenthesis and add the lambda after without the comma.

2017-05-30 11:29 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/Viewer.kt
> +    getObj("feeds", {
You can close the parenthesis and add the lambda after without the comma.

2017-05-30 11:29 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/data/Notifications.kt
> +    val x = json.map<JSONObject, Notification> { Notification(it) }
What is x?

2017-05-30 11:29 UTC, fknop commented on app/src/main/java/gitlin/kothub/utilities/JsonUtilities.kt
> +operator fun JSONArray.iterator(): Iterator<JSONObject>
Why is this needed ? Maybe a foreach instead ?

2017-05-31 10:58 UTC, fknop requested changes

2017-05-31 10:58 UTC, fknop commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".NotificationActivity" />
Move NotificationActivity to ui package

2017-05-31 10:58 UTC, fknop commented on app/src/main/java/gitlin/kothub/MainActivity.kt
> +            startActivity(Intent(this, NotificationActivity::class.java))
Add drawer item instead

2017-05-31 10:58 UTC, fknop commented on app/src/main/java/gitlin/kothub/NotificationActivity.kt
> +        //AppDrawer(this, toolbar)
Add the drawer and select the notifications item after adding it to the drawer

2017-05-31 10:58 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/data/Notifications.kt
> +    private val arr: JsonArray = JsonParser().parse(json).asJsonArray
Would be better to parse it and pass the json array to the notifications object

2017-05-31 11:00 UTC, fknop requested changes

2017-05-31 11:00 UTC, fknop commented on app/src/main/res/layout/activity_notifs.xml
> +
You need to include the toolbar xml file here

2017-05-31 11:21 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/utilities/JsonUtilities.kt
> +operator fun JSONArray.iterator(): Iterator<JSONObject>
It's used here: https://github.com/kothub/kothub/blob/dbc71c61f45be653944327aa98f95de90a62c3f8/app/src/main/java/gitlin/kothub/github/api/Viewer.kt#L69

2017-05-31 11:37 UTC, Astalaseven commented on app/src/main/res/layout/activity_notifs.xml
> +
Done https://github.com/kothub/kothub/pull/13/commits/475d9f4987e5f512071b9189b3630bc00d8f6a25#diff-ca04348500ca962186d699cd2c441654R7

2017-05-31 11:38 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/github/api/data/Notifications.kt
> +    private val arr: JsonArray = JsonParser().parse(json).asJsonArray
Done https://github.com/kothub/kothub/pull/13/commits/475d9f4987e5f512071b9189b3630bc00d8f6a25#diff-1d7244653ed86f90bc94cfff42c6dbccR100

2017-05-31 11:38 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/MainActivity.kt
> +            startActivity(Intent(this, NotificationActivity::class.java))
Done https://github.com/kothub/kothub/pull/13/commits/475d9f4987e5f512071b9189b3630bc00d8f6a25#diff-eb219dfe15e958903f27572f8a62af1eR63

2017-05-31 11:39 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/utilities/JsonUtilities.kt
> +operator fun JSONArray.iterator(): Iterator<JSONObject>
Removed https://github.com/kothub/kothub/pull/13/commits/475d9f4987e5f512071b9189b3630bc00d8f6a25#diff-46b3f60c9247b0f501484437df1a2745L29

2017-05-31 11:40 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/NotificationActivity.kt
> +        //AppDrawer(this, toolbar)
Drawer added https://github.com/kothub/kothub/pull/13/commits/475d9f4987e5f512071b9189b3630bc00d8f6a25#diff-b3d1cb29368e1520fbaf99b2fa2b99e6R41

2017-05-31 13:04 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/Drawer.kt
> +            .addDrawerItems(feed, issues, pulls, notifs, DividerDrawerItem(), settings, DividerDrawerItem(), rate)
Maybe add a divider ?

2017-05-31 15:22 UTC, fknop approved these changes

2017-05-31 15:22 UTC, merged