Notif ui
kothub/kothub pull request #20
Opened 2017-06-02 20:59 UTC by Astalaseven

- [x] Switch to RecyclerView
- [ ] Adapt UI to be more readable

2017-06-04 14:36 UTC, fknop requested changes

2017-06-04 14:36 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/NotificationActivity.kt
>  class NotificationActivity : AppCompatActivity(), AnkoLogger {
Extend the LifecycleAppCompatActivity, create the drawer and add it as a listener. (Need to pull master first)

2017-06-04 14:36 UTC, fknop commented on app/src/main/res/layout/notification_list_view.xml
> +    <View
I think you can add dividers with the recycler view API instead.

2017-06-14 17:30 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/NotificationActivity.kt
>  class NotificationActivity : AppCompatActivity(), AnkoLogger {
Done

2017-06-14 17:44 UTC, fknop requested changes
Fix conflicts with master

2017-06-14 17:44 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/NotificationActivity.kt
> +                val dividerItemDecoration = DividerItemDecoration(notifs.context, layoutManager.orientation)
Is it necessary to create a val for this ?

2017-06-14 17:44 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/NotificationActivity.kt
> +                val dividerItemDecoration = DividerItemDecoration(notifs.context, layoutManager.orientation)
I find it cleaner

2017-06-14 17:57 UTC, fknop approved these changes

2017-06-14 17:57 UTC, merged