Implement Authenticator
kothub/kothub pull request #21
Opened 2017-06-03 22:05 UTC by fknop

WIP - Do not merge

2017-06-11 19:14 UTC, Astalaseven reviewed
A good practice could be to right click on the `java` folder in the Project view and select `Optimize Imports`. That way it does it for the whole project.

2017-06-11 19:14 UTC, Astalaseven commented on app/src/main/assets/github_.css
> +body {
why two different `github.css` ?

2017-06-11 19:14 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/accounts/LoginActivity.kt
> +                putString(AccountManager.KEY_AUTHTOKEN, token)
KEY_AUTH_TOKEN ?

2017-06-11 19:17 UTC, fknop commented on app/src/main/assets/github_.css
> +body {
It was for testing purpose. They are not even used yet.

2017-06-11 19:37 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/github/api/dsl/Edges.kt
> +//abstract class Edges(override val level: Int): Element {
Should clean those before merge

2017-06-11 19:38 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/github/api/dsl/Issue.kt
> +//class IssueEdges(override val level: Int): Edges(level) {
Remove commented code before merge

2017-06-11 19:40 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/github/api/dsl/User.kt
> +//
Remove commented code

2017-06-11 19:41 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/LifecycleAppCompatActivity.kt
> +//        val searchManager = getSystemService(Context.SEARCH_SERVICE) as SearchManager
Remove commented code

2017-06-11 19:43 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/drawer/Drawer.kt
> +                                   "It resets every hour. If you somehow reach zero, you will not be able to use the application until $hour GMT+00:00") {
Remove `somehow`, we shouldn't juge the user

2017-06-11 19:45 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +//        fab.setImageDrawable(
Remove commented code

2017-06-11 19:45 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +//            languageColor.color = Color.parseColor(repo.language.color)
Remove commented code

2017-06-11 19:45 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +                0 -> "Home"
Store const string in strings.xml

2017-06-11 19:46 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/settings/SettingsActivity.kt
> +        //drawer = AppDrawer(this, toolbar)
Remove commented code

2017-06-11 19:52 UTC, Astalaseven requested changes

2017-06-11 19:52 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/utilities/Fragment.kt
> +//    ft.commit()
Remove commented code

2017-06-11 19:52 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/utilities/markdown/HtmlTagHandler.kt
> +        output.append('\u2022')
Can't we use the unicode character `•`?

2017-06-11 19:52 UTC, Astalaseven commented on app/src/main/res/layout/repository_header.xml
> +    <!--<de.hdodenhof.circleimageview.CircleImageView-->
Remove unused code before merge

2017-06-11 19:52 UTC, Astalaseven commented on app/src/main/res/values/styles.xml
> +    <!--<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">-->
Remove unused code before merge

2017-06-12 14:34 UTC, fknop commented on app/src/main/assets/github_.css
> +body {
I removed the files for now.

2017-06-12 14:35 UTC, fknop commented on app/src/main/java/gitlin/kothub/accounts/LoginActivity.kt
> +                putString(AccountManager.KEY_AUTHTOKEN, token)
It's from Android API.

2017-06-12 14:37 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/dsl/Edges.kt
> +//abstract class Edges(override val level: Int): Element {
Done

2017-06-12 14:37 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/dsl/Issue.kt
> +//class IssueEdges(override val level: Int): Edges(level) {
Done

2017-06-12 14:37 UTC, fknop commented on app/src/main/java/gitlin/kothub/github/api/dsl/User.kt
> +//
Done

2017-06-12 14:39 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/drawer/Drawer.kt
> +                                   "It resets every hour. If you somehow reach zero, you will not be able to use the application until $hour GMT+00:00") {
Done

2017-06-12 14:41 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +//        fab.setImageDrawable(
Done

2017-06-12 14:42 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +                0 -> "Home"
Done

2017-06-12 14:42 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/settings/SettingsActivity.kt
> +        //drawer = AppDrawer(this, toolbar)
Done

2017-06-12 14:42 UTC, fknop commented on app/src/main/java/gitlin/kothub/utilities/Fragment.kt
> +//    ft.commit()
Removed the method as it wasn't used.

2017-06-12 14:44 UTC, fknop commented on app/src/main/res/values/styles.xml
> +    <!--<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">-->
Done

2017-06-12 15:15 UTC, Astalaseven requested changes

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/drawer/Drawer.kt
> +fun BadgeStyle.whiteText () = this.withTextColor(android.graphics.Color.WHITE)!!
AS refactor tool for imports seems to have made some undesirable changes

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +    val nameWithOwner: String get() = "$owner/$name"
Property is not more used

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/res/layout/repository_header.xml
> +            android:textSize="16dip"
Use `sp` for textSize

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/res/layout/repository_header.xml
> +            android:textSize="16dip"
Use `sp` for textSize

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/res/layout/repository_header.xml
> +            android:textSize="16dip"
Use `sp` for textSize

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/LauncherActivity.kt
> +        if (accounts.size > 0) {
`accounts.isNotEmpty()` would be more kotlin idiomatic

2017-06-12 15:15 UTC, Astalaseven commented on app/src/main/java/gitlin/kothub/accounts/AccountUtils.kt
> +    if (accounts.size == 0) {
`account.isEmpty()` would be more kotlin idiomatic

2017-06-12 15:23 UTC, fknop commented on app/src/main/java/gitlin/kothub/ui/repo/RepositoryActivity.kt
> +    val nameWithOwner: String get() = "$owner/$name"
I'll let it there for now. It may be useful.

2017-06-12 15:32 UTC, Astalaseven approved these changes

2017-06-12 15:34 UTC, merged